export type ProtectionLevel = 'basic' | 'recommended' | 'maximum'
export type MetadataMode = 'preserve' | 'neutralize'

export type RedactionMode = 'solid' | 'blur' | 'pixelate'

/**
 * Redaction rectangle in normalized coordinates relative to the rendered base.
 * x, y, w, h are all in [0, 1]. Multiply by base intrinsic dimensions to draw.
 * `mode` is fixed at rect creation time so a document can mix modes if the user
 * changes selection mid-session. `color` only applies when mode === 'solid';
 * blur and pixelate ignore it. Values in [0, 1] per channel to match pdf-lib.
 */
export interface RedactionRect {
  id: string
  x: number
  y: number
  w: number
  h: number
  mode: RedactionMode
  color?: { r: number; g: number; b: number }
}

export interface WatermarkText {
  recipient: string
  purpose: string
  date: string
  /**
   * Optional user override. When provided (and non-empty after filtering), these
   * lines replace the recipient/purpose/date lines that would otherwise be
   * generated by formatWatermarkLines.
   */
  custom?: readonly string[]
}

export interface WatermarkOptions {
  text: WatermarkText
  opacity: number
  rotationDeg: number
  fontSize: number
  tile: boolean
  tileGapX: number
  tileGapY: number
  color: { r: number; g: number; b: number }
  /**
   * Per-document seed. Same seed → same output. Set once per file load via
   * crypto.getRandomValues so each protected copy is subtly unique.
   */
  seed: number
  /**
   * Amount of controlled randomization to derive from `seed`. 0 = deterministic
   * regular grid. 1 = maximum wobble that still stays readable. Callers should
   * stay at or below ~0.6 to avoid the "smeared" look.
   */
  jitter: number
  patterns: {
    crosshatch: boolean
    frame: boolean
    /**
     * Distinctly decorative iridescent (holographic-style) gradient overlay.
     * Intentionally reads as a user-added watermark, not as a real official
     * hologram foil.
     */
    iridescent: boolean
    /**
     * Interwoven Lissajous curves reminiscent of banknote guilloche patterns.
     * Purely decorative overlay drawn at low alpha so document content remains
     * readable. Not a claim of authenticity.
     */
    guilloche: boolean
  }
}

export interface ProtectionProfile {
  level: ProtectionLevel
  watermark: WatermarkOptions
  metadata: MetadataMode
}

const BASE_COLOR = { r: 0.1, g: 0.1, b: 0.1 }
const NO_PATTERNS = { crosshatch: false, frame: false, iridescent: false, guilloche: false }

export interface ProfileOverrides {
  crosshatch?: boolean
  frame?: boolean
  iridescent?: boolean
  guilloche?: boolean
  opacity?: number
  rotationDeg?: number
  fontSize?: number
  color?: { r: number; g: number; b: number }
}

export function profileFor(
  level: ProtectionLevel,
  text: WatermarkText,
  seed: number,
  overrides: ProfileOverrides = {},
): ProtectionProfile {
  const base = baseProfile(level, text)
  return {
    ...base,
    watermark: {
      ...base.watermark,
      seed,
      opacity: overrides.opacity ?? base.watermark.opacity,
      rotationDeg: overrides.rotationDeg ?? base.watermark.rotationDeg,
      fontSize: overrides.fontSize ?? base.watermark.fontSize,
      color: overrides.color ?? base.watermark.color,
      patterns: {
        crosshatch: overrides.crosshatch ?? base.watermark.patterns.crosshatch,
        frame: overrides.frame ?? base.watermark.patterns.frame,
        iridescent: overrides.iridescent ?? base.watermark.patterns.iridescent,
        guilloche: overrides.guilloche ?? base.watermark.patterns.guilloche,
      },
    },
  }
}

function baseProfile(level: ProtectionLevel, text: WatermarkText): ProtectionProfile {
  switch (level) {
    case 'basic':
      return {
        level,
        watermark: {
          text,
          opacity: 0.16,
          rotationDeg: -30,
          fontSize: 46,
          tile: false,
          tileGapX: 320,
          tileGapY: 240,
          color: BASE_COLOR,
          seed: 0,
          jitter: 0,
          patterns: NO_PATTERNS,
        },
        metadata: 'preserve',
      }
    case 'recommended':
      return {
        level,
        watermark: {
          text,
          opacity: 0.32,
          rotationDeg: -28,
          fontSize: 14,
          tile: true,
          tileGapX: 320,
          tileGapY: 240,
          color: BASE_COLOR,
          seed: 0,
          jitter: 0,
          patterns: NO_PATTERNS,
        },
        metadata: 'neutralize',
      }
    case 'maximum':
      return {
        level,
        watermark: {
          text,
          opacity: 0.4,
          rotationDeg: -28,
          fontSize: 14,
          tile: true,
          tileGapX: 240,
          tileGapY: 190,
          color: BASE_COLOR,
          seed: 0,
          jitter: 0,
          patterns: { crosshatch: true, frame: true, iridescent: false, guilloche: false },
        },
        metadata: 'neutralize',
      }
  }
}

/** Kept for the smoke test and any legacy callers. Wraps profileFor('recommended'). */
export function defaultWatermarkOptions(text: WatermarkText, seed = 0): WatermarkOptions {
  return profileFor('recommended', text, seed).watermark
}

export function formatWatermarkLines(text: WatermarkText, lang: 'en' | 'es'): string[] {
  if (text.custom && text.custom.length) {
    const trimmed = text.custom.map((l) => l.trim()).filter((l) => l.length > 0)
    if (trimmed.length) return trimmed
  }
  if (lang === 'es') {
    return [
      `COPIA PARA ${text.recipient.toUpperCase()}`,
      `SOLO PARA ${text.purpose.toUpperCase()}`,
      text.date,
    ]
  }
  return [
    `COPY FOR ${text.recipient.toUpperCase()}`,
    `FOR ${text.purpose.toUpperCase()} ONLY`,
    text.date,
  ]
}
